global using ECommerce.Models;
global using ECommerce.Data;
global using ECommerce.Configurations;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using ECommerce.Data.Interfaces;
global using ECommerce.Data.Repositories;
global using Microsoft.AspNetCore.Mvc;
global using System.Linq.Expressions;
global using ECommerce.SD;
// global;
// global;
// global;
// global;